Repository opensearch-project/opensearch-remote-metadata-sdk, pull requests merged in 2025-04, with the labels that each got.

#124 Add a developer guide
  CHANGELOG.md
  DEVELOPER_GUIDE.md
  README.md
Labels: backport 2.x

#128 Ensure consistent reads on DynamoDB getItem calls
  CHANGELOG.md
  ddb-client/src/main/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClient.java
Labels: backport 2.x, backport 2.19

#130 Return 404 for Index not found on Local Cluster search
  CHANGELOG.md
  core/src/main/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClient.java
  core/src/test/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClientTests.java
Labels: backport 2.19

#135 Add 3.0.0.0-beta1 Release Notes
  CHANGELOG.md
  release-notes/opensearch-remote-metadata-sdk.release-notes-3.0.0.0-beta1.md
Labels: backport 2.x

#138 Support phasing off SecurityManager usage in favor of Java Agent
  build.gradle
Labels: skip-changelog, v3.0.0, release

#142 Using java-agent gradle plugin to phase off Security Manager in favor of Java-agent.
  build.gradle
Labels: skip-changelog

#146 Add logging for wrapped completions
  core/src/main/java/org/opensearch/remote/metadata/common/SdkClientUtils.java
Labels: skip-changelog, backport 3.0

#126 Simplify migration and fix exception example
  DEVELOPER_GUIDE.md
Labels: skip-changelog

#150 Work around codecov upload issue
  .github/workflows/CI.yml
Labels: skip-changelog

#158 Properly handle remote client search failures with status codes
  CHANGELOG.md
  core/src/main/java/org/opensearch/remote/metadata/common/SdkClientUtils.java
  remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java
  remote-client/src/test/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClientTests.java
Labels: backport 2.19, backport 3.0

#156 Make generated responses robust to URL encoded id and index values
  CHANGELOG.md
  ddb-client/src/main/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClient.java
  ddb-client/src/test/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClientTests.java
Labels: backport 2.19, backport 3.0

#157 Validate request fields in DDB Put and Update implementations
  CHANGELOG.md
  ddb-client/src/main/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClient.java
  ddb-client/src/test/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClientTests.java
Labels: backport 2.19, backport 3.0

#164 Add 3.0.0.0 Release Notes
  CHANGELOG.md
  release-notes/opensearch-remote-metadata-sdk.release-notes-3.0.0.0.md
Labels: backport 3.0

#166 Remove beta1 qualifier
  build.gradle
Labels: v3.0.0, release, backport main
