Repository opensearch-project/opensearch-remote-metadata-sdk, pull requests merged in 2025-06, with the labels that each got.

#198 Add release notes
  CHANGELOG.md
  release-notes/opensearch-remote-metadata-sdk.release-notes-3.1.0.0.md
Labels: backport 3.1

#201 Fix CVE-2025-27820
  build.gradle
Labels: skip-changelog, backport 3.1

#200 Update the maven snapshot publish endpoint and credential
  .github/workflows/publish-snapshots.yml
  build.gradle
Labels: skip-changelog

#205 Exclude httpclient5 from checkstyle import to resolve CVE
  build.gradle
Labels: skip-changelog, backport main
