Repository opensearch-project/opensearch-remote-metadata-sdk, pull requests merged in 2025-03, with the labels that each got.

#114 Fix version conflict check
  CHANGELOG.md
  core/src/main/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClient.java
  core/src/test/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClientTests.java
Labels: backport 2.x

#115 [Backport 2.x] Fix version conflict check (#114)
  CHANGELOG.md
  core/src/main/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClient.java
  core/src/test/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClientTests.java
Labels: backport 2.19

#119 Add 3.0.0.0-alpha1 Release Notes
  release-notes/opensearch-remote-metadata-sdk.release-notes-3.0.0.0-alpha1.md
Labels: skip-changelog

#121 Use SdkClientDelegate's classloader for ServiceLoader
  CHANGELOG.md
  aos-client/src/test/java/org/opensearch/remote/metadata/client/impl/AOSSdkClientFactoryTests.java
  core/src/main/java/org/opensearch/remote/metadata/client/impl/SdkClientFactory.java
  ddb-client/src/test/java/org/opensearch/remote/metadata/client/impl/DDBSdkClientFactoryTests.java
  remote-client/src/test/java/org/opensearch/remote/metadata/client/impl/RemoteSdkClientFactoryTests.java
Labels: backport 2.x, backport 2.19
