Repository opensearch-project/opensearch-remote-metadata-sdk, pull requests merged in 2025-01, with the labels that each got.

#23 Add workflow to add backport 2.x label automatically when PR opened
  .github/workflows/add-backport-label.yml
  .github/workflows/backport.yml
Labels: skip-changelog

#21 Use docker CI image for Linux build (#15)
  .github/workflows/CI.yml
Labels: skip-changelog, backport 2.x

#27 Actually define the snapshot repo so we can publish to it
  build.gradle
Labels: skip-changelog, backport 2.x

#29 Switch publication to shadow JAR and add build script
  .github/workflows/publish-snapshots.yml
  aos-client/build.gradle
  build.gradle
  core/build.gradle
  ddb-client/build.gradle
  remote-client/build.gradle
  scripts/build.sh
Labels: skip-changelog, backport 2.x

#36 Use latest version of checkstyle to avoid Guava CVE
  build.gradle
Labels: skip-changelog, backport 2.x

#38 choosing jackson version from core
  build.gradle
Labels: skip-changelog, backport 2.x

#40 upgrading httpclient5 and httpcore5 with core version
  build.gradle
Labels: skip-changelog

#43 Revert "Switch publication to shadow JAR and add build script (#29)"
  .github/workflows/publish-snapshots.yml
  aos-client/build.gradle
  build.gradle
  core/build.gradle
  ddb-client/build.gradle
  remote-client/build.gradle
  scripts/build.sh
Labels: skip-changelog, backport 2.x

#47 Allow specifying a default Executor when instantiating SdkClient
  core/src/main/java/org/opensearch/remote/metadata/client/SdkClient.java
  core/src/main/java/org/opensearch/remote/metadata/client/impl/SdkClientFactory.java
  core/src/test/java/org/opensearch/remote/metadata/client/SdkClientTests.java
Labels: skip-changelog, backport 2.x

#45 Add build script to onboard to OpenSearch release
  build.gradle
  formatter/formatting.gradle
  scripts/build.sh
Labels: skip-changelog, backport 2.x

#53 Use async NodeClient APIs for LocalClusterIndicesClient
  core/src/main/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClient.java
  core/src/test/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClientTests.java
Labels: skip-changelog, backport 2.x

#56 Use version catalog for log4j and mockito versions
  build.gradle
Labels: skip-changelog, backport 2.x

#61 [Release 3.0] Bump main branch to use revision 3.0.0.0-alpha1
  build.gradle
  core/src/test/java/org/opensearch/remote/metadata/client/impl/LocalClusterIndicesClientTests.java
Labels: skip-changelog, backport 2.x, v3.0.0, release
