Repository opensearch-project/opensearch-remote-metadata-sdk, pull requests merged in 2025-02, with the labels that each got.

#68 Fix codecov upload for codecov-action v5
  .github/workflows/CI.yml
Labels: skip-changelog

#67 Improve exception unwrapping flexibility for SdkClientUtils
  CHANGELOG.md
  core/src/main/java/org/opensearch/remote/metadata/common/SdkClientUtils.java
  core/src/test/java/org/opensearch/remote/metadata/common/SdkClientUtilsTests.java
Labels: backport 2.x

#78 Refactor SDKClientUtil for better readability, fix javadocs
  core/src/main/java/org/opensearch/remote/metadata/common/SdkClientUtils.java
Labels: skip-changelog, backport 2.x, backport 2.19

#79 Make DynamoDBClient fully async
  CHANGELOG.md
  ddb-client/src/main/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClient.java
  ddb-client/src/test/java/org/opensearch/remote/metadata/client/impl/DDBOpenSearchClientTests.java
Labels: backport 2.x

#93 Fixes CVE-2025-24970
  CHANGELOG.md
  build.gradle
Labels: backport 2.x, backport 2.19

#101 Fix checkstyle to actually run on subprojects
  build.gradle
Labels: skip-changelog, backport 2.x

#102 Update deprecated features in Gradle build
  build.gradle
  core/build.gradle
Labels: skip-changelog, backport 2.x

#80 Make Remote Cluster Client and AOS client fully async
  CHANGELOG.md
  aos-client/src/main/java/org/opensearch/remote/metadata/client/impl/AOSOpenSearchClient.java
  aos-client/src/test/java/org/opensearch/remote/metadata/client/impl/AOSOpenSearchClientTests.java
  remote-client/src/main/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClient.java
  remote-client/src/test/java/org/opensearch/remote/metadata/client/impl/RemoteClusterIndicesClientTests.java
Labels: backport 2.x
